name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install package
        run: pnpm i --frozen-lockfile

      - name: Check
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Format Check
        run: pnpm format:check
